modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/cech12/BrickShears/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="brickhopper"
    version="${file.jarVersion}"
    displayName="Brick Hopper"
    displayURL="https://github.com/cech12/BrickHopper"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds a Brick Hopper.
    '''
[[dependencies.brickhopper]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.56,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brickhopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"